### ISSUE TITLE
¿Funciona?

### ISSUE THREAD

**Issue by jjprz** [ldotlopez/ha-pepephone#1]
Me gustaría integrar los datos de Pepephone en Home Assistant y he visto este proyecto aunque parece que está en proceso. Personalmente he intentado hacer el login en la web pero sin éxito.

**Comment by ldotlopez** [comment]
Hola,

La integración como tal no funciona, no hay código que Home Assistant pueda utilizar.
Hasta ahora solo está implementado un API preliminar para comunicarse con Pepephone pero nada más.

De momento estoy centrado en otros proyectos y no puedo dedicarle tiempo (aunque no lo descarto en el futuro).

Cualquier contribución es bien recibida de todos modos.
